services:
  postgres:
    image: postgres:15.2

    volumes:
      # Persistent data storage
      - postgres-data:/var/lib/postgresql/data

      # Persistent server data
      - ./tools/postgres/postgres.conf/postgres.conf:/etc/postgresql/postgresql.conf

      # Persistent logs data
      - ./tools/postgres/logs:/logs

    environment:
      POSTGRES_DB: 'user'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

    ports:
      - '5432:5432'

    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

    restart: always

volumes:
  postgres-data:
