@url = http://localhost:3003/bff-api
@user_api_url = http://localhost:3001/user-api

### BFF-API Health
Get {{url}}/health

### BFF-API User
### delete user by id
DELETE {{url}}/user/59

### update user by id
PATCH {{url}}/user/70
Content-Type: application/json

{
    "name":"Example name IV"
}

### Example Method
# Query Options:
#   cat_fact=""
#   throw_me_an_error=ERROR_TYPE  <-- can be: NOT_FOUND | INTERNAL_SERVER_ERROR | FORBIDDEN | ... See the @llove/models/shared/interfaces/service-manager for more.
Get {{url}}/user/example-method?cat_fact=""

### USER-API
### get users
GET {{user_api_url}}/user/all